version: '3'

networks:
  bdd:

services:
  npm:
    networks:
      - bdd
    build:
      dockerfile: npm.Dockerfile
    volumes:
      - .:/var/opt/app
    working_dir: /var/opt/app
    ports:
      - "4200:4200"
  selenium:
    networks:
      - bdd
    image: seleniarm/standalone-chromium:114.0
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: '2gb'
