name: Deploy to Main

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_VERSION: '24'

jobs:
  post-merge-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run comprehensive test suite
        run: |
          echo "🧪 Running unit tests..."
          npm run test

          echo "🔍 Running linting..."
          npm run lint

          echo "🏗️ Running build..."
          npm run build

      - name: Security audit on main
        run: |
          echo "🔒 Running security audit..."
          npm audit --audit-level=moderate

  e2e-smoke-tests:
    runs-on: ubuntu-latest
    needs: post-merge-validation

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
          - 7900:7900
        options: --shm-size=2gb

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install

      - name: Wait for Selenium
        run: |
          timeout 60s bash -c 'until curl -f http://localhost:4444/wd/hub/status; do sleep 2; done'

      - name: Run E2E smoke tests
        run: npm run e2e:ci
        env:
          SELENIUM_HOST: localhost

      - name: Upload E2E artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: main-e2e-failure-artifacts
          path: |
            .tmp/
            allure-results/
          retention-days: 14

  build:
    runs-on: ubuntu-latest
    needs: [post-merge-validation, e2e-smoke-tests]

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build production assets
        run: npm run build
